### ISSUE TITLE
Error "Cannot read property 'X' of undefined" when using records-data in included jade-template-partital

### ISSUE THREAD

**Issue by marcelreschke** [carrot/roots-records#10] opened 2015-04-06 12:13 UTC
Hi there,

When I try to display a JSON key/value pair in an included jade template partial, I get the following error:

**Error:**
```
compiling... ✘ Error: TypeError: heldenschaum-site/views/blocks/header.jade:1
  > 1| h1= JSON.stringify(block.id)
    2| 

Cannot read property 'id' of undefined

Potentially unhandled rejection [34] TypeError: heldenschaum-site/views/blocks/header.jade:1
  > 1| h1= JSON.stringify(block.id)
    2| 

Cannot read property 'id' of undefined
  at eval (<anonymous>:12:77)
  at eval (<anonymous>:17:22)
  at res (heldenschaum-site/node_modules/jade/lib/index.js:219:38)
```

**header.jade:**
```
h1= JSON.stringify(block.id)
```

**index.jade:**
```
extends layout

block content
  for block in records.blocks
    case block.type
      when 'header'
        include blocks/header
        h1= block.properties.title
        h2= block.properties.subtitle
      
  :markdown
  Find tutorials and documentation at http://roots.cx : )
```

***blocks.json:***
```
{ "data":
  {
    "id":"1",
    "type":"header",
    "test":"test",
    "properties":{
      "title":"Title",
      "subtitle":"Subtitle",
      "bgcolor":"blue"
    }
  }
}
```

***extension configuration:***
```
records(blocks: {file:'data/blocks.json', path:'data'})
```

I tried different keys, always the same error. Records data can be accessed in index.jade perfectly and when I modify header.jade to:
```
h1= JSON.stringify(block)
```
The h1-headline displays correctly:
```
{"id":"1","type":"header","test":"test","properties":{"title":"Title","subtitle":"Subtitle","bgcolor":"blue"}}
```

I'm not sure if it is a real issue or it is my fault. Please have a look.

Thanks in advance and for awesome roots generally.
Marcel Reschke

**Comment by jenius** [comment] 2015-04-08 00:51
Ah, I see the issue. Put an underscore before the partial's name. So call it `blocks/_header`. The issue is that since the partial is not ignored, roots is trying to compile it on its own, out of context, which is generating that error.

I'm going to close this out since the above solution will fix it guaranteed :grinning:

**Closed by jenius** 2015-04-08 00:51 UTC
